server:
  jwt_key: 324mIOjkm34k677NkfsJf3
  server_host:
  server_port: 8081
  metrics_host:
  metrics_port: 8082

database:
  db_name: postgres
  db_user: postgres
  db_password: postgres
  db_driver: postgres
  db_host: db
  db_port: 5432

logger:
  level: info