events {
    worker_connections  1024;
}

http {
    server {
        listen 80;

        set $base_path /Users/dmitry/Desktop/bmstu/7sem/bmstu-web/nginx;
        root $base_path;

        location / {
            root $base_path/static;
        }

        location /documentation {
            root /Users/dmitry/Desktop/bmstu/7sem/bmstu-web;
            index README.md;
            allow all;
        }

        location = /api/v2/ {
            proxy_pass http://localhost:3000/;
        }

        location /api/v2/ {
            proxy_pass http://localhost:8081/api/v2/;
        }

        location /api/v2/swagger/ {
            proxy_pass http://localhost:3000/;
        }

        location /legacy/ {
            alias $base_path/legacy/;
        }

#         location ~* /api/v2/(.*)(\.(css|js|json|map|html|png|yaml)?$) {
#             proxy_pass http://localhost:8081/$1$2;
#         }

        location /test/ {
            proxy_pass http://localhost/;
        }

        location /admin/ {
            proxy_set_header X-Script-Name /admin;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header Host $host;
            proxy_pass http://localhost:5050/;
            proxy_redirect off;
        }

        location = /status/ {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}