events {
    worker_connections  1024;
}

http {
#     error_log /opt/homebrew/var/log/nginx/error.log debug;

     upstream balanced_backend {
        server localhost:8081 weight=2;
        server localhost:8083;
        server localhost:8084;
    }

    server {
        listen 80;

        set $base_path /Users/dmitry/Desktop/bmstu/7sem/bmstu-web/nginx;
        root $base_path;

        location / {
            root $base_path/static;
        }

        location /documentation {
            add_header 'Content-Type' 'text/markdown; charset=utf-8';
            root /Users/dmitry/Desktop/bmstu/7sem/bmstu-web;
            index README.md;
            allow all;
        }

        location = /api/v2/ {
            proxy_pass http://localhost:3000/;
        }

        location /api/v1/ {
            if ( $request_method ~ ^(PATCH|POST)$ ) {
                proxy_pass http://localhost:8081;
            }
            if ( $request_method ~ ^(GET)$ ) {
                proxy_pass http://balanced_backend;
            }
        }

        location /api/v2/ {
            if ( $request_method ~ ^(PATCH|POST)$ ) {
                proxy_pass http://localhost:8081;
            }
            if ( $request_method ~ ^(GET)$ ) {
                proxy_pass http://balanced_backend;
            }
        }

        location /api/v2/swagger/ {
            proxy_pass http://localhost:3000/;
        }

        location /legacy/ {
            alias $base_path/legacy/;
        }

        location /test/ {
            proxy_pass http://localhost/;
        }

        location /admin/ {
            proxy_set_header X-Script-Name /admin;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header Host $host;
            proxy_pass http://localhost:5050/;
            proxy_redirect off;
        }

        location = /status/ {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}